// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Leaderboards", b =>
                {
                    b.Property<string>("ShadowKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("KD_Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MMR")
                        .HasColumnType("int");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("deaths")
                        .HasColumnType("int");

                    b.Property<string>("fav_agent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kills")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShadowKey");

                    b.HasAlternateKey("username", "Pname");

                    b.ToTable("player_leaderboard_users", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.agents", b =>
                {
                    b.Property<string>("agent_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("pick_pct")
                        .HasColumnType("real");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suited_weapon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ultimate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voiced_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("win_pct")
                        .HasColumnType("real");

                    b.HasKey("agent_name");

                    b.ToTable("Agents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
